### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by connordoner** [breakthroughparty/project-wp-mw-sso#3]
Is this still under development, and is it in use anywhere?

**Comment by soup-bowl** [comment]
Abandoned, along with the concept that required it (@GeoCyberwolf can speak for that). It was transferred from my account as I wasn't able to dedicate time to it, so it can be archived.

**Comment by connordoner** [comment]
Thanks, @soup-bowl! Is it currently in a workable state? If not, I'll likely delete it.

**Comment by soup-bowl** [comment]
Never got to actually starting the code, but has a fleshed out Docker setup for bridging WP to MW.

If you’re planning on deleting it, are you happy for me to return this back to my account? Happy to do it myself if approved, but I can salvage the CI for a template.
